export const DummyData = [
    {
        id: 1,
        Nombre: "Miguel",
        Apellido: "Alveo",
        Posicion: "Desarrollador Junior",
        Departamento: "Dev team",
        Supervisor: "Alfonso Alvarado",
        FechaDesde: "hoy",
        FechaHasta: "manana",
        Descripcion: "Laptop",
        Concepto: "Laptop",
        Cuenta: "400.00 USD",
        Total: "400.00 USD",
        AprobadoPor: "Alfonso Alvarado", 
    },
    {
        id: 2,
        Nombre: "Alfonso",
        Apellido: "Alvarado",
        Posicion: "Desarrollador Senior",
        Departamento: "Dev Team",
        Supervisor: "",
        FechaDesde: "Hoy",
        FechaHasta: "Manana",
        Descripcion: "Laptop",
        Concepto: "Laptop",
        Cuenta: "500.00 USD",
        Total: "500.00 USD",
        AprobadoPor: "Alfonso Alvarado", 
    }, 
];
